In [1]:
import numpy as np
from IPython.display import display
import pandas as pd

In [3]:
# 1
np.random.seed(80)
rand_array = np.random.randint(1, 101, (4, 4))
display(rand_array)

array([[48, 61, 39, 84],
       [11, 51,  4, 87],
       [24, 16, 82,  6],
       [65, 10, 93, 43]])

In [7]:
# a
display('rand_array > 50', rand_array[(rand_array > 50)])

'rand_array > 50'

array([61, 84, 51, 87, 82, 65, 93])

In [47]:
# b
print('sum axis=0 columns:\n', rand_array.sum(axis=0))
print('\nsum axis=1 rows:\n', rand_array.sum(axis=1))

sum axis=0 columns:
 [148 138 218 220]

sum axis=1 rows:
 [232 153 128 211]


In [49]:
# c.i.
print('maximum of each column:\n', np.max(rand_array, axis=0))
print('\nmaximum of each row:\n', np.max(rand_array, axis=1))

maximum of each column:
 [65 61 93 87]

maximum of each row:
 [84 87 82 93]


In [51]:
# c. ii.
print('minimum of each column:\n', np.min(rand_array, axis=0))
print('\nminimum of each row:\n', np.min(rand_array, axis=1))

minimum of each column:
 [11 10  4  6]

minimum of each row:
 [39  4  6 10]


In [53]:
# c. iii.
print('average of each column:\n', np.mean(rand_array, axis=0))
print('\naverage of each row:\n', np.mean(rand_array, axis=1))

average of each column:
 [37.  34.5 54.5 55. ]

average of each row:
 [58.   38.25 32.   52.75]


In [55]:
# 2
new_games = {
"Final Fantasy VII Rebirth": 69.99,
"Astro Bot": 59.99,
"Star Wars Outlaws": 69.99,
"Silent Hill 2 Remake": 69.99,
"Elden Ring: Shadow of the Erdtree": 39.99,
"Dragon Age: The Veilguard": 69.99,
"Metaphor: ReFantazio": 59.99
}

In [65]:
# a
games_series = pd.Series(new_games)
display("price of 'Metaphor: ReFantazio':", games_series["Metaphor: ReFantazio"])

"price of 'Metaphor: ReFantazio':"

59.99

In [67]:
# b
display('keys (index) of the series:',games_series.keys())

'keys (index) of the series:'

Index(['Final Fantasy VII Rebirth', 'Astro Bot', 'Star Wars Outlaws',
       'Silent Hill 2 Remake', 'Elden Ring: Shadow of the Erdtree',
       'Dragon Age: The Veilguard', 'Metaphor: ReFantazio'],
      dtype='object')

In [69]:
# c
display("price of the game at index 3:", games_series.iloc[3])

'price of the game at index 3:'

69.99

In [81]:
# d
display('total price of all games:', games_series.values.sum())

'total price of all games:'

439.93

In [112]:
# 3
# a
from skimage import io
photo = io.imread('jinny.jpg')

print(type(photo))
print(photo.shape)
print(photo[125][100])

import matplotlib.pyplot as plt
plt.imshow(photo)

FileNotFoundError: No such file: 'C:\Users\קרין\jinny.jpg'

In [114]:
# b
display(photo[:, :50])

NameError: name 'photo' is not defined

In [116]:
# c
from PIL import Image
photo = io.imread('imoji.jpg')
photo_pil = Image.fromarray(photo)
photo = photo_pil.rotate(120)
import matplotlib.pyplot as plt
plt.imshow(photo)

FileNotFoundError: No such file: 'C:\Users\קרין\imoji.jpg'